"""dc.type -> work-type map (oxjob #544 / I10).

Generated from oxjob #545 rules_manifest.tsv (channel=dc.type, precision>=93.0%,
n>=10). dc.type is taxicab landing-page metadata (tx_meta), non-circular. Re-measured
on held-out gold_full_52k in I10. Regenerate: python -m cascade_classifier.gen_dctype_map
"""

DCTYPE_MAP = {
    'araştırma makalesi': 'article',
    'article': 'article',
    'article-commentary': 'editorial',
    'articles': 'article',
    'artigo original': 'article',
    'artigos': 'article',
    'artículos': 'article',
    'artículos científicos': 'article',
    'artículos de investigación': 'article',
    'artículos originales': 'article',
    'book reviews': 'book-review',
    'book-review': 'book-review',
    'bookreview': 'book-review',
    'case report': 'article',
    'case reports': 'article',
    'case-report': 'article',
    'chapter': 'book-chapter',
    'communication': 'article',
    'congress-abstract': 'conference-abstract',
    'correction': 'erratum',
    'dissertação': 'dissertation',
    'doctoral dissertation': 'dissertation',
    'dossiê': 'article',
    'editorial': 'editorial',
    'editorialnotes': 'editorial',
    'makaleler': 'article',
    'meeting-report': 'conference-abstract',
    'news': 'other',
    'original articles': 'article',
    'original papers': 'article',
    'original research': 'article',
    'oxan-executive-summary': 'report',
    'papers': 'article',
    'pg_thesis': 'dissertation',
    'rapid-communication': 'article',
    'research article': 'article',
    'research articles': 'article',
    'research papers': 'article',
    'reseñas': 'book-review',
    'retraction': 'retraction',
    'review': 'review',
    'review article': 'review',
    'thesis': 'dissertation',
}
