"""Single-type source allowlists (oxjob #544 / I8).

Generated from oxjob #547 single-type-source-catalog (evidence/single-type-sources.csv +
work/candidates.json, gold-frac >= 0.90) and data/preprint_servers.csv. Kept signals are
name-match for all 5 types (measured >= 0.95 precision on gold_master) and DOI-prefix for
preprint only (0.985; other types' prefixes were too broad and dropped at the 0.86 bar).
The 5 dataset-mixed repos (Zenodo/Figshare/Dataverse/Mendeley/OSF) are excluded.
Regenerate with cascade_classifier.gen_source_lists (python -m).
"""

CONFPAPER_NAMES = frozenset({
    'acl anthology',
    'acta horticulturae',
    'advances in economics, business and management research',
    'advances in economics, business and management research (atlantis)',
    'advances in economics, business and management research/advances in economics, business and management research',
    'advances in intelligent systems and computing (aisc)',
    'advances in neural information processing systems (neurips)',
    'advances in neural information processing systems 36',
    'advances in social science, education and humanities research',
    'advances in social science, education and humanities research (atlantis)',
    'advances in social science, education and humanities research/advances in social science, education and humanities research',
    'aiaa papers (scitech / aviation / propulsion & energy)',
    'aip conference proceedings',
    'anais do encontro nacional de engenharia de produção',
    'asme international mechanical engineering congress proceedings',
    'ceur workshop proceedings',
    'coastal engineering proceedings',
    'communications in computer and information science',
    'communications in computer and information science (ccis)',
    'conference on lasers and electro-optics',
    'conference on lasers and electro-optics (cleo)',
    'conference proceedings of the society for experimental mechanics',
    'destech transactions',
    'e3s web of conferences',
    'ecs transactions',
    'edulearn proceedings',
    'electronic proceedings in theoretical computer science (eptcs)',
    'energy procedia',
    'epic series in computing',
    'epj web of conferences',
    'frontiers in artificial intelligence and applications (ios press)',
    'hawaii international conf. on system sciences (hicss) proceedings',
    'iabse reports',
    'iceri proceedings',
    'iet conference proceedings',
    'iet conference proceedings.',
    'ifac proceedings volumes',
    'ifac-papersonline',
    'ifip advances in information and communication technology',
    'ifmbe proceedings',
    'inted proceedings',
    'international petroleum technology conference (iptc)',
    'iop conf. series: earth and environmental science',
    'iop conf. series: materials science and engineering',
    'iop conference series earth and environmental science',
    'iop conference series materials science and engineering',
    'iop conference series: earth and environmental science',
    'iop conference series: materials science and engineering',
    'isca interspeech archive',
    'isprs annals of the photogrammetry, remote sensing & spatial info sci.',
    'isprs annals of the photogrammetry, remote sensing and spatial information sciences',
    'isprs archives of the photogrammetry, remote sensing & spatial info sci.',
    'itm web of conferences',
    'journal of physics conference series',
    'journal of physics: conference series',
    'lecture notes in civil engineering',
    'lecture notes in computer science',
    'lecture notes in computer science (lncs)',
    'lecture notes in networks and systems',
    'lecture notes of the inst. for computer sciences (lnicst)',
    'lecture notes of the institute for computer sciences, social informatics and telecommunications engineering',
    'lecture notes on data engineering and communications technologies',
    "lipics (leibniz int'l proceedings in informatics)",
    'matec web of conferences',
    'materials research proceedings',
    'materials today proceedings',
    'materials today: proceedings',
    'mrs proceedings',
    'mrs proceedings (materials research society)',
    'nuclear physics b: proceedings supplements',
    'proc. of the human factors and ergonomics society annual meeting',
    'procedia - social and behavioral sciences',
    'procedia cirp / manufacturing / chemistry / structural integrity',
    'procedia computer science',
    'procedia engineering',
    'proceedings of machine learning research (pmlr / icml, aistats)',
    'proceedings of spie, the international society for optical engineering/proceedings of spie',
    'proceedings of the 2020 aera annual meeting',
    'proceedings of the aaai conference on artificial intelligence',
    'proceedings of the acm on programming languages (pacmpl)',
    'proceedings of the international astronomical union',
    'proceedings of the language resources and evaluation conf. (lrec)',
    'proceedings of the language resources and evaluation conference',
    'proceedings of the vldb endowment (pvldb)',
    'proceedings of the water environment federation',
    'sae technical paper series',
    'sae technical papers on cd-rom/sae technical paper series',
    'scitepress proceedings',
    'sgem international multidisciplinary scientific geoconference',
    'sgem international multidisciplinary scientific geoconference expo proceedings',
    'shs web of conferences',
    'sid symposium digest of technical papers',
    'spe improved oil recovery conference',
    'spie proceedings',
    'springer proceedings in physics',
    'the european proceedings of social & behavioural sciences',
    'the proceedings of the jsme annual meeting',
    'usenix proceedings',
    'vdi verlag ebooks',
    'world congress on medical physics and biomedical engineering, september 7 - 12, 2009, munich, germany',
    '\x98the \x9ceuropean proceedings of social & behavioural sciences',
    '\x98the \x9cinternational archives of the photogrammetry, remote sensing and spatial information sciences/international archives of the photogrammetry, remote sensing and spatial information sciences',
})

CONFABS_NAMES = frozenset({
    'abstracts',
    'abstracts with programs - geological society of america',
    'academy of management proceedings',
    'acta crystallographica section a foundations and advances',
    'acta crystallographica section a — meeting abstracts',
    'annals of oncology — esmo congress abstract supplements',
    'archives of cardiovascular diseases supplements',
    'atherosclerosis supplements',
    'blood — ash annual meeting abstract supplements',
    'bone abstracts',
    'cancer research — aacr meeting abstract supplements',
    'circulation — aha scientific sessions abstract supplements',
    'diabetes — ada scientific sessions abstract supplements',
    'ecs meeting abstracts',
    'endocrine abstracts',
    'european psychiatry',
    'european psychiatry — epa congress abstracts',
    'european urology open science',
    'european urology open science — abstracts',
    'european urology supplements',
    'geological society of america abstracts with programs',
    'goldschmidt abstracts',
    'gsa abstracts with programs (geological society of america)',
    'haematologica — eha congress abstract supplements',
    'innovation in aging',
    'innovation in aging — gsa abstracts',
    'isee conference abstracts',
    'journal of clinical oncology — asco meeting abstract supplements',
    'journal of the endocrine society',
    'journal of the endocrine society — abstract supplements',
    'medicine & science in sports & exercise — acsm abstracts',
    'medicine &amp; science in sports &amp; exercise',
    'microscopy and microanalysis',
    'microscopy and microanalysis — meeting abstracts',
    'neurology — aan annual meeting abstract supplements',
    'proc. annual convention of the japanese psychological association',
    'the faseb journal',
    'the faseb journal — meeting supplements',
    'the journal of heart and lung transplantation',
    'the journal of heart and lung transplantation — abstract suppl.',
    'the proceedings of the annual convention of the japanese psychological association',
    'value in health',
    'value in health — ispor abstracts',
})

DATAPAPER_NAMES = frozenset({
    'big earth data',
    'biodiversity data journal',
    'bmc genomic data',
    'chemical data collections',
    'data (mdpi)',
    'data in brief',
    'data intelligence',
    'data science journal',
    'earth system science data (essd)',
    'genome announcements',
    'geoscience data journal',
    'gigascience / gigabyte',
    'journal of open humanities data',
    'journal of open psychology data',
    'microbiology resource announcements (genome/data announcements)',
    'open data journal for agricultural research',
    'open health data',
    'scientific data',
})

DATASET_NAMES = frozenset({
    '4tu.researchdata',
    'addgene',
    'aea randomized controlled trials',
    'aea rct registry',
    'arrayexpress',
    'biomodels',
    'biostudies',
    'cambridge structural database (csd)',
    'chemical effects in biological systems (cebs)',
    'clinicaltrials.gov',
    'clinvar',
    'crystallography open database (cod)',
    'datasets - sistema salve - icmbio',
    'dbgap',
    'dbsnp',
    'dryad',
    'earthchem',
    'electron microscopy data bank (emdb)',
    'encode',
    'encode datasets',
    'european genome-phenome archive (ega)',
    'european nucleotide archive (ena)',
    'gabii project',
    'gabii project reports database',
    'gbif (global biodiversity information facility)',
    'genbank / ncbi nucleotide',
    'gisaid',
    'gwas catalog',
    'http://isrctn.com/',
    'icpsr',
    'igvf datasets',
    'inorganic crystal structure database (icsd)',
    'isrctn registry',
    'iucn red list of threatened species',
    'materials project',
    'metabolights',
    'morphosource',
    'morphosource media',
    'movebank',
    'ncbi gene expression omnibus (geo)',
    'neuromorpho.org',
    'openneuro',
    'pangaea',
    'proteomexchange / pride',
    'psyctests (apa)',
    'psyctests dataset',
    'salve — icmbio',
    'sequence read archive (sra)',
    'treebase',
    'uk data service',
    'uniprot',
    'worldwide protein data bank',
    'worldwide protein data bank (wwpdb)',
})

PREPRINT_NAMES = frozenset({
    'african research repository',
    'africarxiv',
    'agri-archive',
    'agrirxiv',
    'aijr preprint server',
    'aijr preprints',
    'alternative e-print archive',
    'apsa preprints',
    'apsa preprints on cambridge open engage',
    'arxiv',
    'arxiv.org',
    'authorea',
    'authorea preprints',
    'beilstein archive',
    'beilstein archives',
    'biohackrxiv',
    'biohackrxiv preprints',
    'biology preprint server',
    'biorxiv',
    'biorxiv (cold spring harbor laboratory)',
    'biorxiv.org',
    'cambridge open engage',
    'chemrxiv',
    'chemrxiv preprints',
    'chinaxiv',
    'chinaxiv.org',
    'coe',
    'criminology archive',
    'crimrxiv',
    'cryptology eprint archive',
    'e-print archive',
    'earth and space science open archive',
    'earth archive',
    'eartharxiv',
    'easychair preprints',
    'eccc',
    'ecoevo archive',
    'ecoevorxiv',
    'ecs archive',
    'ecsarxiv',
    'ecsarxiv preprints',
    'edarxiv',
    'edarxiv preprints',
    'education archive',
    'electronic colloquium on computational complexity',
    'engineering archive',
    'engrxiv',
    'engrxiv preprints',
    'ess open archive',
    'ess open archive (essoar)',
    'essoar',
    'health sciences preprint server',
    'iacr eprint archive',
    'in review',
    'india archive',
    'indianrxiv',
    'indiarxiv',
    'japan preprint server',
    'jmir preprints',
    'jxiv',
    'jxiv (jst, japan)',
    'law archive',
    'lawarxiv',
    'lingbuzz',
    'lingbuzz archive',
    'marxiv',
    'media archive',
    'mediarxiv',
    'mediarxiv preprints',
    'medrxiv',
    'medrxiv.org',
    'metaarxiv',
    'metaarxiv preprints',
    'nutrixiv',
    'osf preprints',
    'paleontology archive',
    'paleorxiv',
    'philarchive',
    'philosophy e-print archive',
    'philosophy of science archive',
    'philpapers archive',
    'philsci-archive',
    'preprints.org',
    'preprints.org (mdpi)',
    'preprints.ru',
    'psyarxiv',
    'psyarxiv preprints',
    'psychology archive',
    'qeios',
    'qeios preprints',
    'repec working papers',
    'research square',
    'research square (research square)',
    'research square preprints',
    'roa',
    'russian preprint server',
    'rutgers optimality archive',
    'scielo preprints',
    'scielo preprints collection',
    'scienceopen preprints',
    'socarxiv',
    'socarxiv preprints',
    'social science research network',
    'socopen',
    'sportrxiv',
    'sportrxiv preprints',
    'ssrn',
    'ssrn electronic journal',
    'ssrn first look',
    'techrxiv',
    'under review',
    'vixra',
    'vixra.org',
    'yale law archive',
})

PREPRINT_PREFIXES = frozenset({
    '10.1101',
    '10.20944',
    '10.21203',
    '10.2139',
    '10.26434',
    '10.64898',
})
